## Define an example tensor

In [102]:
%reset -f
import numpy as np
epsilon = np.array([[1.0, 2.1, 3.5],
                  [2.1, 3.0, 1.2],
                  [3.5, 1.2, 2.0]], dtype=np.float_)

## Evaluate invariants using einsum

\begin{align}
\label{eq:I_1}
    I_1 = \varepsilon_{ii}
\end{align}

In [103]:
I_1 = np.einsum('ii', epsilon)
print 'I_1', I_1

I_1 6.0


\begin{align}
\label{eq:I_2}
I_2 &= \frac{1}{2} \left[ \varepsilon_{kk}^2 - \varepsilon_{ij}\varepsilon_{ij} \right]
\end{align}

In [104]:
I_2 = 1/2.*(np.einsum('kk',epsilon)**2 - np.einsum('ij,ij', epsilon, epsilon))
print 'I_2', I_2

I_2 -7.100000000000001


\begin{align}
\label{eq:I_3}
I_3 &= \epsilon_{ijk} \varepsilon_{i1} \varepsilon_{j2} \varepsilon_{k3}.
\end{align}
where $\epsilon$ represents the Levi Civita symbol rendering the value 1 for ascending indexes, i.e. (1,2,3), (2,3,1), (3,1,2), value -1 for descending indexes (3,2,1), (1,3,2), (2,1,3) and zero otherwise

In [105]:
EPS = np.zeros((3, 3, 3), dtype='f')
EPS[(0, 1, 2), (1, 2, 0), (2, 0, 1)] = 1
EPS[(2, 1, 0), (1, 0, 2), (0, 2, 1)] = -1
I_3 = np.einsum('ijk,i,j,k',EPS,epsilon[:,0],epsilon[:,1],epsilon[:,2],)
print 'I_3', I_3

I_3 -23.369999999999997


## Get the principle strains and eigenvectors

In [106]:
eps1, Q1 = np.linalg.eig(epsilon)
print 'principal strains\n', eps1
print 'principal vectors\n', Q1.T

principal strains
[ 6.53923547 -2.17920041  1.63996494]
principal vectors
[[-0.58515271 -0.54942327 -0.59643137]
 [-0.77897767  0.17643487  0.60171798]
 [ 0.22536657 -0.81670362  0.5312298 ]]


Transform the strain tensor to the direction of principal vectors, check if the shear strains are really zero? What are the values on the diagonal? 

In [107]:
epsilon2 = np.einsum('im,jn,ij->mn',Q1,Q1,epsilon)
print 'rotated epsilon\n', epsilon2

rotated epsilon
[[ 6.53923547e+00  2.44249065e-15  3.33066907e-16]
 [ 2.22044605e-15 -2.17920041e+00 -3.33066907e-16]
 [ 5.55111512e-16 -3.33066907e-16  1.63996494e+00]]


Put the principal strains onto a diagonal and make to construct the tensor in the coordinate system given by the principal strain directions

In [110]:
DELTA = np.identity(3)
epsilon3 = np.einsum('ik,jk,k->ij', DELTA, DELTA, eps1)

Here the Kroneker delta has been used to expand a vector to a rank-2 tensor 
(Consider the analogy to matrix operators)
What will be the eigenvalues and eigenvectors of this tensor?

In [111]:
eps3, Q3 = np.linalg.eig(epsilon3)
print 'eigenvalues\n', eps3
print 'eigenvectors\n', Q3

eigenvalues
[ 6.53923547 -2.17920041  1.63996494]
eigenvectors
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Deviatoric strain

In [112]:
epsilon_d = epsilon - I_1 / 3.0

In [113]:
J_1 = np.einsum('ii', epsilon_d)
J_1

0.0

In [114]:
J_2 = 1/2.*(np.einsum('kk',epsilon_d)**2 - np.einsum('ij,ij', epsilon_d, epsilon_d))
print 'J_2', J_2

J_2 -3.9000000000000004


In [115]:
EPS = np.zeros((3, 3, 3), dtype='f')
EPS[(0, 1, 2), (1, 2, 0), (2, 0, 1)] = 1
EPS[(2, 1, 0), (1, 0, 2), (0, 2, 1)] = -1
J_3 = np.einsum('ijk,i,j,k',EPS,epsilon_d[:,0],epsilon_d[:,1],epsilon_d[:,2],)
print 'J_3', J_3

J_3 -1.85
